int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int _evaluate (int i, int n);
int is_prime_number(int n);
int evaluate_num(int num, int iterator);
int is_palindrome(char *s);
int _strlen_recursion(char *s);
int is_palindrome(char *s);
int evaluate(char *s, int i, int size, int add);
